### ISSUE TITLE
Post imputation checklist

### ISSUE THREAD

**Issue by megan-soria** [markziemann/Gene-function-imputation#13]
- [x] make a new df from original GO input matrix with blinded genes = 0 GOs

- [x] make the same correlation analysis 

# maybe do this for 10 clusters
- [x] Do the comparison for cluster 1 and check accuracy and precision by matrix subtraction (blinded df- original df)

- [x] tweak parameters: (1) correlation threshold, (2) number of clusters (*the higher accuracy, the better), and/or (3) use another clustering method like K-Means

**Comment by megan-soria** [comment]
task 4 related to 
commit#: a952aa59b407d4895e013926eaa6595648bee326
